# This workflow uses actions that are not certified by GitHub.
# Estas las proporcionan entidades terceras y las gobiernan
# condiciones de servicio, políticas de privacidad y documentación de soporte
# documentación.

name: Publish Docker image

on:
  push:
    branches:
      - 'main'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: docker.io/osmond/sample-page
          tags: |
            type=raw,value={{branch}}-{{sha}}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  push_to_repo:
    # needs: push_to_registry
    name: Push chart to repository
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: docker.io/osmond/sample-page
          tags: |
            type=raw,value={{branch}}-{{sha}}
      - name: Install helm
        run : |
          curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
          sudo apt-get install apt-transport-https --yes
          echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
          sudo apt-get update
          sudo apt-get install helm
          helm plugin install https://github.com/thynquest/helm-pack.git
          helm pack deploy/chart --set containerImage=docker.io/osmond/sample-page:${{ steps.meta.outputs.labels }}
          cp /home/runner/work/sample-page/sample-page/osmond-sample-page-0.2.1.tgz /home/runner/work/_temp/osmond-sample-page-0.2.1.tgz
      - name: Check out my other private repo
        uses: actions/checkout@v2
        with:
          repository: Xosmond/helm-charts
          token: ${{ secrets.GIT_TOKEN }}
      - name: Push to repo
        run : |
          git config --global user.email "bot@osmond.club"
          git config --global user.name "Osmond bot"
          cp /home/runner/work/_temp/osmond-sample-page-0.2.1.tgz /home/runner/work/sample-page/sample-page/osmond-sample-page-0.2.1.tgz
          git add .
          git commit -m "New version"
          git push origin main